### ISSUE TITLE
проблемы при сборке под debian 11

### ISSUE THREAD

**Issue by hypeq** [vectozavr/3dzavr#6]
In file included from /home/hype/3dzavr/engine/network/ClientUDP.cpp:5:
/home/hype/3dzavr/engine/network/ClientUDP.h:15:59: error: incomplete type ‘std::numeric_limits<double>’ used in nested name specifier
   15 |     double _lastBroadcast = -std::numeric_limits<double>::max();
      |                                                           ^~~
make[2]: *** [CMakeFiles/3dzavr.dir/build.make:468: CMakeFiles/3dzavr.dir/engine/network/ClientUDP.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/3dzavr.dir/all] Ошибка 2
make: *** [Makefile:91: all] Ошибка 2

**Comment by aw4yout** [comment]
Проблему решить легко, открываешь ClientUDP.h в любом текстовом редакторе и в начале файла пишешь `#include <limits>`
